"""Added soft delete and revoke fields

Revision ID: 5cfdbbd43606
Revises: a1f9aa8e4029
Create Date: 2026-05-09 10:24:54.970630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cfdbbd43606'
down_revision = 'a1f9aa8e4029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_revoked', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('admin_audit_log', schema=None) as batch_op:
        batch_op.drop_column('is_revoked')

    # ### end Alembic commands ###
