"""Add profile settings columns

Revision ID: a71f000c5db4
Revises: 5cfdbbd43606
Create Date: 2026-05-09 11:02:35.818128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71f000c5db4'
down_revision = '5cfdbbd43606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('daily_study_goal', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('daily_study_goal')
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
